### PR TITLE
Erase rows during Repair mode and add Partial Mode

### LINKED ISSUE #2: Repair mode should delete the line automatically
When repairing lines, code should be generated to simply delete the line first, thus avoiding having to do each one manually.

If I get the chance, I will PR this myself. But just wanted to open the discussion.

### PR DESCRIPTION
**Pull request by JonathanNye**
Fixes #2 

During repair mode, the macro will now pre-clear specified rows before going back and re-drawing them.

I still liked the behavior that it used to have for some use cases, so I broke that out as "Partial" mode.

Somewhat self-servingly, I expanded the behavior of the preview images as well -- Orange pixels now call out areas of the canvas that are visited by the drawing cursor but won't be modified. This made it a little easier to see what would happen on Partial/Repair modes.

### CODE REVIEW

**Comment by zaventh** [comment]
@JonathanNye This works great. Definitely makes repairing rows faster and less manual.

I did have to change the following otherwise I received a compilation error:

```diff
diff --git a/src/main/kotlin/Img2Splat.kt b/src/main/kotlin/Img2Splat.kt
index b9571d2..8a12deb 100644
--- a/src/main/kotlin/Img2Splat.kt
+++ b/src/main/kotlin/Img2Splat.kt
@@ -401,7 +401,7 @@ class Img2Splat(private val options: Options) {
                 is Options.TraversalMode.Repair -> {
                     macro.repairImage(options.img, options.traversalMode.repairRows)
                 }
-                null -> {
+                else -> {
                     macro.drawImage(options.img, null, options.cautious)
                 }
             }
```

It's related to exhaustive `when`s which I believe became an error in 1.7.0.

At any rate, it seems to work well with this one change :+1:

**Comment by JonathanNye** [comment]
Whoops! I refactored how the Options were modeled as a bit of an afterthought and forgot to fix the consuming side. Will fix, thanks!

**Review by zaventh — APPROVED** [review]
LGTM

**Comment by zaventh** [comment]
@JonathanNye Doesn't look like I can merge it just FYI.

**Pull request merged**
